import { useEffect, useMemo, useRef, useState } from 'react'
import { Activity, Bell, Box, ChevronRight, CloudSun, FileText, Gauge, Leaf, MapPin, Menu, RotateCcw, Search, Settings, ShieldCheck, Sparkles, UserRound, X, Zap } from 'lucide-react'
import Globe from './Globe'
import { SectionView, type DashboardSection } from './Sections'
import { fetchDashboardData, type DashboardData } from './api'
import { stations } from './stations'
import { batteryPercent, renewableShare } from './telemetry'
import type { Station, TwinTelemetry } from './types'

const nav: { label: DashboardSection; icon: typeof Gauge }[] = [{ label: 'Overview', icon: Gauge }, { label: 'Energy', icon: Zap }, { label: 'Systems', icon: Box }, { label: 'AI & Forecast', icon: Sparkles }, { label: 'Digital Twin', icon: Activity }, { label: 'Environment', icon: CloudSun }, { label: 'Reports', icon: FileText }]
const projectStation = stations.find((station) => station.id === 'bharati')!
const stationTelemetry = (_station: Station, dashboardData: DashboardData | null): TwinTelemetry | null => dashboardData?.currentTelemetry ?? null
type SearchResult =
  | { kind: 'station'; label: string; section: DashboardSection; station: Station }
  | { kind: 'section'; label: DashboardSection; section: DashboardSection }

function Metric({ label, value, unit, trend, icon: Icon, tint, onClick }: { label: string; value: string; unit: string; trend: string; icon: typeof Zap; tint: string; onClick: () => void }) { return <button className={`metric-card ${tint}`} onClick={onClick} aria-label={`Open ${label}`}><span className="metric-icon"><Icon size={23} /></span><div><p>{label}</p><strong>{value}<em>{unit}</em></strong></div><span className="trend">{trend}</span></button> }

function PolarMap({ selected, onSelect }: { selected: Station; onSelect: (station: Station) => void }) { return <div className="polar-map" role="region" aria-label="Antarctic research network map"><div className="map-grid" />{stations.map((station) => { const radians = station.longitude * Math.PI / 180; const radius = Math.min(43, (90 + station.latitude) * 1.9); const style = { left: `${50 + Math.sin(radians) * radius}%`, top: `${50 - Math.cos(radians) * radius}%` }; return <button key={station.id} className={`map-node ${selected.id === station.id ? 'selected' : ''}`} style={style} onClick={() => onSelect(station)}><i /><span>{station.name}</span></button> })}<div className="map-key">POLAR NETWORK MAP · project simulation node in green</div></div> }
function StationList({ selected, onSelect }: { selected: Station; onSelect: (station: Station) => void }) { return <div className="station-list">{stations.map((station) => <button key={station.id} className={selected.id === station.id ? 'selected' : ''} onClick={() => onSelect(station)}><i className={station.source === 'aurora-simulation' ? 'simulated' : ''} /><span><b>{station.name}</b><small>{station.source === 'aurora-simulation' ? 'AURORA-EMS SIMULATION' : 'RESEARCH NETWORK REFERENCE'}</small></span><ChevronRight size={16} /></button>)}</div> }

export default function App() {
  const [selected, setSelected] = useState<Station>(projectStation); const [active, setActive] = useState<DashboardSection>('Overview'); const [view, setView] = useState<'globe' | 'map' | 'stations'>('globe'); const [resetToken, setResetToken] = useState(0); const [query, setQuery] = useState(''); const [noticesOpen, setNoticesOpen] = useState(false); const [profileOpen, setProfileOpen] = useState(false); const [mobileOpen, setMobileOpen] = useState(false); const [dashboardData, setDashboardData] = useState<DashboardData | null>(null); const [dashboardError, setDashboardError] = useState<string | null>(null); const [dashboardLoading, setDashboardLoading] = useState(true)
  const noticesRef = useRef<HTMLDivElement>(null); const profileRef = useRef<HTMLDivElement>(null)
  useEffect(() => { const close = (event: MouseEvent) => { if (!noticesRef.current?.contains(event.target as Node)) setNoticesOpen(false); if (!profileRef.current?.contains(event.target as Node)) setProfileOpen(false) }; document.addEventListener('mousedown', close); return () => document.removeEventListener('mousedown', close) }, [])
  useEffect(() => { let active = true; fetchDashboardData().then((data) => { if (active) { setDashboardData(data); setDashboardError(null) } }).catch((error: unknown) => { if (active) setDashboardError(error instanceof Error ? error.message : 'Unable to load dashboard data') }).finally(() => { if (active) setDashboardLoading(false) }); return () => { active = false } }, [])
  useEffect(() => { if (selected.id !== projectStation.id) setSelected(projectStation) }, [selected])
  useEffect(() => { const currentTelemetry = dashboardData?.currentTelemetry; if (currentTelemetry) window.dispatchEvent(new CustomEvent('aurora-globe-data', { detail: { telemetry: currentTelemetry, stormRisk: dashboardData.forecast.rows[0]?.storm_risk_flag ?? false, connectivityStatus: dashboardData.resilience.connectivity_status } })) }, [dashboardData])
  const telemetry = stationTelemetry(selected, dashboardData); const currentTime = useMemo(() => new Intl.DateTimeFormat('en-GB', { hour: '2-digit', minute: '2-digit', hour12: false, timeZone: 'UTC' }).format(new Date()), []); const energyOutput = telemetry ? telemetry.totalLoadKw.toFixed(1) : '—'; const currentRenewableShare = telemetry ? renewableShare(telemetry) : null; const currentBatteryPercent = telemetry ? batteryPercent(telemetry) : null
  const navigate = (section: DashboardSection) => { setActive(section); setMobileOpen(false); setQuery(''); window.scrollTo({ top: 0, behavior: 'smooth' }) }; const selectStation = (station: Station) => { if (station.id === projectStation.id) setSelected(projectStation); setView('globe') }
  const searchResults: SearchResult[] = query.trim() ? [...stations.filter((station) => station.name.toLowerCase().includes(query.toLowerCase())).map((station) => ({ kind: 'station' as const, label: station.name, section: 'Overview' as DashboardSection, station })), ...nav.filter((item) => item.label.toLowerCase().includes(query.toLowerCase()) || (item.label === 'Energy' && /battery|solar|wind/.test(query.toLowerCase()))).map((item) => ({ kind: 'section' as const, label: item.label, section: item.label }))] : []
  return <main className="app-shell min-h-screen"><aside className={`sidebar ${mobileOpen ? 'mobile-open' : ''}`}><div className="brand"><span className="brand-mark">◆</span><div><b>AURORA-EMS</b><small>Polar Station Energy Management</small></div></div><nav>{nav.map(({ label, icon: Icon }) => <button key={label} className={active === label ? 'active' : ''} onClick={() => navigate(label)}><Icon size={19} />{label}</button>)}</nav><div className="side-aurora"><span>SUSTAINABLE TODAY<br />BRIGHTER TOMORROW</span></div><div className="system-online"><i /> <div><b>Simulation Online</b><small>Prototype telemetry active</small></div></div></aside>
    <section className="content"><header className="topbar"><button className="mobile-menu" onClick={() => setMobileOpen((value) => !value)} aria-label="Toggle navigation"><Menu /></button><div className="search-wrap"><div className="search"><Search size={19} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search stations, data, or insights..." aria-label="Search dashboard" />{query ? <button onClick={() => setQuery('')} aria-label="Clear search"><X size={15} /></button> : <kbd>Ctrl K</kbd>}</div>{searchResults.length > 0 && <div className="search-results">{searchResults.map((result, index) => <button key={`${result.label}-${index}`} onClick={() => { if (result.kind === 'station') setSelected(result.station); navigate(result.section) }}><Search size={14} /><span>{result.label}<small>{result.kind === 'station' ? 'Station' : 'Section'}</small></span></button>)}</div>}</div><div className="operator"><div className="popover-wrap" ref={noticesRef}><button onClick={() => setNoticesOpen((value) => !value)} aria-label="Open notifications"><Bell size={19} /></button>{noticesOpen && <div className="popover notices"><b>System notices</b><p><i /> No active unmet-load alerts in the verified Twin sample.</p><p><i className="blue-dot" /> Bharati telemetry is simulated/prototype data.</p></div>}</div><div className="profile-wrap" ref={profileRef}><button className="profile-button" onClick={() => setProfileOpen((value) => !value)} aria-label="Open operator menu"><span className="avatar">AR</span><div><b>AURORA-EMS</b><small>Research Operator</small></div></button>{profileOpen && <div className="popover profile-menu"><b>Research Operator</b><button onClick={() => navigate('Systems')}><Gauge size={15} /> System Status</button><button disabled title="Settings are not configured in this prototype"><Settings size={15} /> Settings unavailable</button></div>}</div></div></header>
      {dashboardError && <div className="reference-empty"><b>Dashboard data unavailable</b><span>{dashboardError}</span></div>}{active === 'Overview' ? <><section className="hero"><div><p className="eyebrow">POLAR DIGITAL TWIN · SIMULATED TELEMETRY</p><h1>Polar Station<br /><span>Energy Command Center</span></h1><p className="hero-copy">Energy intelligence for the AURORA-EMS Bharati research-station simulation.</p></div><div className="hero-time"><span>Simulation clock · UTC</span><strong>{currentTime}<small> UTC</small></strong><p><MapPin size={25} /> Bharati, Antarctica<br /><small>69.4069° S, 76.1956° E</small></p></div></section><section className="metrics"><Metric label="Station Load" value={energyOutput} unit="kW" trend={telemetry ? 'TWIN OUTPUT' : 'LOADING'} icon={Zap} tint="amber" onClick={() => navigate('Energy')} /><Metric label="Renewable Contribution" value={currentRenewableShare === null ? '—' : String(currentRenewableShare)} unit="%" trend={telemetry ? `${telemetry.renewableUsedKw.toFixed(1)} kW` : 'LOADING'} icon={Leaf} tint="mint" onClick={() => navigate('Energy')} /><Metric label="Battery State" value={currentBatteryPercent === null ? '—' : String(currentBatteryPercent)} unit="%" trend={telemetry ? `${telemetry.batterySocKwh.toFixed(1)} kWh` : 'LOADING'} icon={CloudSun} tint="blue" onClick={() => navigate('Environment')} /><Metric label="Critical Load" value={telemetry ? (telemetry.criticalLoadServed ? '100' : '0') : '—'} unit="%" trend={telemetry ? 'SERVED' : 'LOADING'} icon={ShieldCheck} tint="green" onClick={() => navigate('Systems')} /></section>
        <section className="mission-grid"><article className="globe-panel glass-panel"><div className="panel-toolbar"><div><button className={view === 'globe' ? 'selected' : ''} onClick={() => setView('globe')}><Activity size={17} /> Globe</button><button className={view === 'map' ? 'selected' : ''} onClick={() => setView('map')}><MapPin size={16} /> Map</button><button className={view === 'stations' ? 'selected' : ''} onClick={() => setView('stations')}><MapPin size={16} /> Stations</button></div><button className="reset" onClick={() => { setView('globe'); setSelected(stations[0]); setResetToken((value) => value + 1) }} title="Center Antarctica"><RotateCcw size={17} /> Center Antarctica</button></div><div className="globe-canvas">{view === 'globe' && <Globe selected={selected} onSelect={selectStation} resetToken={resetToken} />}{view === 'map' && <PolarMap selected={selected} onSelect={selectStation} />}{view === 'stations' && <StationList selected={selected} onSelect={selectStation} />}<div className="globe-caption"><span className="live-dot" />{view === 'globe' ? 'LIVE DIGITAL TWIN' : view === 'map' ? 'POLAR NETWORK MAP' : 'STATION NETWORK'}<small>{view === 'globe' ? 'Drag to rotate · scroll to zoom · select a node' : 'Select a station to inspect'}</small></div></div><div className="network-footer"><span><MapPin /> <b>1</b><small>Modeled Station</small></span><span><Activity /> <b>4</b><small>Reference Nodes</small></span><span><Gauge /> <b>{telemetry?.unmetLoadKw === 0 ? '100%' : '—'}</b><small>Load Served</small></span><span><Leaf /> <b>{telemetry?.unmetLoadKw === 0 ? '0' : '—'}</b><small>Unmet Load kW</small></span></div></article>
          <aside className="right-rail"><article className="station-detail glass-panel"><header><h2>Station Telemetry</h2><ChevronRight /></header><div className="station-top"><span className="station-pulse reference" /><div><b>Bharati</b><small>India · Online</small></div><span>LIVE TWIN</span></div>{telemetry ? <><div className="telemetry"><div><small>STATION LOAD</small><b>{telemetry.totalLoadKw}<em> kW</em></b></div><div><small>AMBIENT</small><b>{telemetry.temperatureC}°<em>C</em></b></div><div><small>FUEL</small><b>{Math.round(telemetry.fuelRemainingLitres)}<em> L</em></b></div></div><p className="provenance">Verified Digital Twin sample · {telemetry.timestamp} UTC</p></> : <div className="reference-empty"><b>Loading AURORA-EMS telemetry</b><span>Requesting the Bharati Digital Twin sample.</span></div>}</article><article className="energy-mix glass-panel"><header><h2>Energy Mix <small>(TWIN)</small></h2><button className="text-action" onClick={() => navigate('Energy')}>View Details →</button></header>{telemetry ? <div className="mix-body"><div className="donut"><span><b>{telemetry.totalLoadKw}</b>kW</span></div><div className="energy-readings"><small>ENERGY SOURCES</small><ul><li><i className="solar" />Solar <b>{telemetry.solarPowerKw.toFixed(1)} kW</b></li><li><i className="wind" />Wind <b>{telemetry.windPowerKw.toFixed(1)} kW</b></li><li><i className="generator" />Generator <b>{telemetry.generatorTotalKw.toFixed(1)} kW</b></li></ul><small>BATTERY</small><p>SOC <b>{telemetry.batterySocKwh.toFixed(1)} kWh</b></p><p>Discharge <b>{telemetry.batteryDischargeKw.toFixed(1)} kW</b></p></div></div> : <div className="reference-empty"><b>Energy mix unavailable</b><span>Waiting for the Bharati Digital Twin sample.</span></div>}</article></aside></section>
        <section className="feature-grid"><button onClick={() => navigate('AI & Forecast')}><span className="feature-icon blue"><Sparkles /></span><h3>AI Forecast</h3><p>Open available forecast context.</p><ChevronRight /></button><button onClick={() => navigate('Digital Twin')}><span className="feature-icon cyan"><Box /></span><h3>Digital Twin</h3><p>Open simulation context and input signals.</p><ChevronRight /></button><button onClick={() => navigate('Environment')}><span className="feature-icon green"><Leaf /></span><h3>Environment</h3><p>View current Twin weather conditions.</p><ChevronRight /></button><button onClick={() => navigate('Reports')}><span className="feature-icon blue"><FileText /></span><h3>Reports</h3><p>Export the current simulation summary.</p><ChevronRight /></button></section></> : <SectionView section={active} onNavigate={navigate} telemetry={telemetry} telemetryHistory={dashboardData?.telemetryHistory} forecast={dashboardData?.forecast} dispatch={dashboardData?.dispatch} resilience={dashboardData?.resilience} provenance={dashboardData?.provenance} apiError={dashboardError} loading={dashboardLoading} />}
    </section></main>
}
