import { useState } from 'react'
import { Activity, ArrowDownToLine, Battery, BrainCircuit, CloudSun, Cpu, FileText, Gauge, Leaf, Wind, Zap } from 'lucide-react'
import { batteryPercent, bharatiTelemetry, renewableShare } from './telemetry'

export type DashboardSection = 'Overview' | 'Energy' | 'Systems' | 'AI & Forecast' | 'Digital Twin' | 'Environment' | 'Reports'

const telemetry = bharatiTelemetry

function DetailCard({ label, value, detail, icon: Icon }: { label: string; value: string; detail: string; icon: typeof Zap }) { return <article className="detail-card"><span><Icon size={20} /></span><small>{label}</small><b>{value}</b><p>{detail}</p></article> }

export function SectionView({ section, onNavigate }: { section: Exclude<DashboardSection, 'Overview'>; onNavigate: (section: DashboardSection) => void }) {
  const [selectedSystem, setSelectedSystem] = useState('Critical load service')
  const downloadReport = () => {
    const csv = `metric,value,unit\nStation load,${telemetry.totalLoadKw},kW\nRenewable used,${telemetry.renewableUsedKw},kW\nSolar,${telemetry.solarPowerKw},kW\nWind,${telemetry.windPowerKw},kW\nGenerator,${telemetry.generatorTotalKw},kW\nBattery SOC,${telemetry.batterySocKwh},kWh\nFuel remaining,${telemetry.fuelRemainingLitres},L\nUnmet load,${telemetry.unmetLoadKw},kW\n`
    const url = URL.createObjectURL(new Blob([csv], { type: 'text/csv' }))
    const link = document.createElement('a'); link.href = url; link.download = 'aurora-ems-bharati-simulation-summary.csv'; link.click(); URL.revokeObjectURL(url)
  }
  const title = section === 'AI & Forecast' ? 'AI & Forecast' : section
  return <section className="section-view glass-panel"><header className="section-heading"><div><p className="eyebrow">AURORA-EMS · SIMULATED / PROTOTYPE DATA</p><h2>{title}</h2></div><button onClick={() => onNavigate('Overview')}>Back to overview</button></header>
    {section === 'Energy' && <><div className="detail-grid"><DetailCard label="Station Load" value={`${telemetry.totalLoadKw} kW`} detail="Supplied simulation load" icon={Zap} /><DetailCard label="Renewable Used" value={`${telemetry.renewableUsedKw.toFixed(1)} kW`} detail={`${renewableShare}% of station load`} icon={Leaf} /><DetailCard label="Battery SOC" value={`${telemetry.batterySocKwh} kWh`} detail={`${batteryPercent}% of installed capacity`} icon={Battery} /><DetailCard label="Generator" value={`${telemetry.generatorTotalKw} kW`} detail="Twin dispatch output" icon={Cpu} /></div><div className="flow-strip"><b>ENERGY FLOW</b><span>Solar {telemetry.solarPowerKw.toFixed(1)} kW</span><i>→</i><span>Wind {telemetry.windPowerKw.toFixed(1)} kW</span><i>→</i><span>Station load {telemetry.totalLoadKw} kW</span></div></>}
    {section === 'Systems' && <><div className="systems-list"><button onClick={() => setSelectedSystem('Critical load service')}><i className="healthy" /><span><b>Critical load service</b><small>{telemetry.criticalLoadServed ? 'Served by current Twin result' : 'Not served'}</small></span><strong>{telemetry.criticalLoadServed ? 'Nominal' : 'Alert'}</strong></button><button onClick={() => setSelectedSystem('Battery storage')}><i className="healthy" /><span><b>Battery storage</b><small>{telemetry.batterySocKwh} kWh state of charge</small></span><strong>{batteryPercent}% SOC</strong></button><button onClick={() => setSelectedSystem('Diesel generation')}><i className={telemetry.generatorTotalKw > 0 ? 'healthy' : 'idle'} /><span><b>Diesel generation</b><small>Current Digital Twin dispatch</small></span><strong>{telemetry.generatorTotalKw} kW</strong></button><button onClick={() => onNavigate('Digital Twin')}><i className="healthy" /><span><b>Digital Twin simulation</b><small>Open source simulation context</small></span><strong>Open →</strong></button></div><div className="system-detail"><small>SELECTED SYSTEM</small><b>{selectedSystem}</b><span>{selectedSystem === 'Critical load service' ? `${telemetry.unmetLoadKw} kW unmet load in the current Twin result.` : selectedSystem === 'Battery storage' ? `${telemetry.batterySocKwh} kWh currently stored (${batteryPercent}% capacity).` : `${telemetry.generatorTotalKw} kW dispatched by the current Twin result.`}</span></div></>}
    {section === 'AI & Forecast' && <div className="empty-state"><BrainCircuit /><div><b>Forecast service not connected</b><p>The current repository exposes a validated weather input and Digital Twin simulation, but no forecast API or trained forecasting model. The latest measured/simulated load is shown below without fabricating a prediction.</p></div><div className="actual-reading"><small>ACTUAL TWIN LOAD</small><b>{telemetry.totalLoadKw} kW</b><span>Forecast horizon: unavailable</span></div></div>}
    {section === 'Digital Twin' && <div className="detail-grid"><DetailCard label="Simulation Timestamp" value={telemetry.timestamp.replace('T', ' ')} detail="Verified 24-hour sample" icon={Activity} /><DetailCard label="Load Served" value={telemetry.unmetLoadKw === 0 ? '100%' : 'Partial'} detail={`${telemetry.unmetLoadKw} kW unmet load`} icon={Gauge} /><DetailCard label="Fuel Remaining" value={`${Math.round(telemetry.fuelRemainingLitres)} L`} detail="Carried-forward Twin state" icon={Battery} /><DetailCard label="Weather Input" value={`${telemetry.temperatureC}°C`} detail={`${telemetry.windSpeedMs} m/s wind · ${telemetry.irradianceWm2} W/m²`} icon={CloudSun} /></div>}
    {section === 'Environment' && <div className="detail-grid"><DetailCard label="Ambient Temperature" value={`${telemetry.temperatureC}°C`} detail="Digital Twin weather input" icon={CloudSun} /><DetailCard label="Wind Speed" value={`${telemetry.windSpeedMs} m/s`} detail="Digital Twin weather input" icon={Wind} /><DetailCard label="Solar Irradiance" value={`${telemetry.irradianceWm2} W/m²`} detail="Digital Twin weather input" icon={Zap} /><DetailCard label="Solar Generation" value={`${telemetry.solarPowerKw.toFixed(1)} kW`} detail="Calculated PV output" icon={Leaf} /></div>}
    {section === 'Reports' && <div className="report-summary"><div><FileText /><h3>Bharati simulation summary</h3><p>Contains the active AURORA-EMS telemetry fields shown in this dashboard. All figures are simulation/prototype data.</p></div><button onClick={downloadReport}><ArrowDownToLine size={17} /> Download CSV</button></div>}
  </section>
}
