import { useState } from 'react'
import { Activity, ArrowDownToLine, Battery, BrainCircuit, CloudSun, Cpu, FileText, Gauge, Leaf, Wind, Zap } from 'lucide-react'
import { batteryPercent, renewableShare } from './telemetry'
import type { DashboardPayload, TwinTelemetry } from './types'

export type DashboardSection = 'Overview' | 'Energy' | 'Systems' | 'AI & Forecast' | 'Digital Twin' | 'Environment' | 'Reports'
function DetailCard({ label, value, detail, icon: Icon }: { label: string; value: string; detail: string; icon: typeof Zap }) { return <article className="detail-card"><span><Icon size={20} /></span><small>{label}</small><b>{value}</b><p>{detail}</p></article> }
function Unavailable({ message }: { message: string }) { return <div className="empty-state"><BrainCircuit /><div><b>Data unavailable</b><p>{message}</p></div></div> }
const num = (value: number, digits = 1) => value.toFixed(digits)

export function SectionView({ section, onNavigate, telemetry, telemetryHistory = [], forecast = { available: false, horizon_hours: 0, rows: [] }, dispatch, resilience, provenance, apiError, loading }: { section: Exclude<DashboardSection, 'Overview'>; onNavigate: (section: DashboardSection) => void; telemetry: TwinTelemetry | null; telemetryHistory?: TwinTelemetry[]; forecast?: DashboardPayload['forecast']; dispatch?: DashboardPayload['dispatch']; resilience?: DashboardPayload['resilience']; provenance?: DashboardPayload['provenance']; apiError: string | null; loading: boolean }) {
  const [selectedSystem, setSelectedSystem] = useState('Critical load service')
  if (!telemetry) return <section className="section-view glass-panel"><header className="section-heading"><div><p className="eyebrow">AURORA-EMS · SIMULATED / PROTOTYPE DATA</p><h2>{section}</h2></div><button onClick={() => onNavigate('Overview')}>Back to overview</button></header><Unavailable message={loading ? 'Loading the dashboard API response…' : apiError ?? 'No Bharati telemetry is available.'} /></section>
  const renewablePercent = renewableShare(telemetry); const socPercent = batteryPercent(telemetry); const latestDispatch = dispatch?.history[dispatch.history.length - 1]; const nextForecast = forecast?.available ? forecast.rows[0] : undefined; const resilienceLatest = resilience?.latest
  const reportRows = [['Telemetry samples', String(telemetryHistory.length)], ['Forecast rows', String(forecast?.rows.length ?? 0)], ['Dispatch steps', String(dispatch?.history.length ?? 0)], ['Fuel used', `${num(dispatch?.summary.optimized_fuel_used_litres ?? 0)} L`], ['Fuel remaining', `${num(telemetry.fuelRemainingLitres)} L`], ['Resilience', resilience?.connectivity_status ?? 'Unavailable']]
  const downloadReport = () => { const csv = `metric,value\n${reportRows.map(([metric, value]) => `${metric},${value}`).join('\n')}\n`; const url = URL.createObjectURL(new Blob([csv], { type: 'text/csv' })); const link = document.createElement('a'); link.href = url; link.download = 'aurora-ems-bharati-simulation-summary.csv'; link.click(); URL.revokeObjectURL(url) }
  return <section className="section-view glass-panel"><header className="section-heading"><div><p className="eyebrow">AURORA-EMS · SIMULATED / PROTOTYPE DATA</p><h2>{section}</h2></div><button onClick={() => onNavigate('Overview')}>Back to overview</button></header>
    {section === 'Energy' && <><div className="detail-grid"><DetailCard label="Renewable Used" value={`${num(latestDispatch?.renewable_used_kw ?? telemetry.renewableUsedKw)} kW`} detail={`${renewablePercent}% of current load`} icon={Leaf} /><DetailCard label="Battery Flow" value={`${num((latestDispatch?.battery_charge_kw ?? 0) - (latestDispatch?.battery_discharge_kw ?? 0))} kW`} detail={`${num(telemetry.batterySocKwh)} kWh SOC`} icon={Battery} /><DetailCard label="Generator Output" value={`${num(latestDispatch?.generator_total_kw ?? telemetry.generatorTotalKw)} kW`} detail={`${num(latestDispatch?.generator_1_kw ?? 0)} / ${num(latestDispatch?.generator_2_kw ?? 0)} kW`} icon={Cpu} /><DetailCard label="Fuel Remaining" value={`${num(latestDispatch?.fuel_remaining_litres ?? telemetry.fuelRemainingLitres)} L`} detail={`${num(dispatch?.summary.optimized_fuel_used_litres ?? 0)} L used`} icon={Gauge} /></div><div className="flow-strip"><b>BACKEND DISPATCH</b><span>Curtailed {num(latestDispatch?.renewable_curtailed_kw ?? 0)} kW</span><i>→</i><span>Unmet {num(latestDispatch?.unmet_load_kw ?? telemetry.unmetLoadKw)} kW</span><i>→</i><span>Flexible shed {num(latestDispatch?.flexible_load_shed_kw ?? 0)} kW</span></div></>}
    {section === 'Systems' && <><div className="systems-list"><button onClick={() => setSelectedSystem('Generator fleet')}><i className={telemetry.generatorTotalKw > 0 ? 'healthy' : 'idle'} /><span><b>Generator fleet</b><small>Output {num(telemetry.generatorTotalKw)} kW</small></span><strong>{telemetry.generatorTotalKw > 0 ? 'Running' : 'Idle'}</strong></button><button onClick={() => setSelectedSystem('Battery storage')}><i className="healthy" /><span><b>Battery storage</b><small>{num(telemetry.batterySocKwh)} kWh state of charge</small></span><strong>{socPercent}% SOC</strong></button><button onClick={() => setSelectedSystem('Critical load service')}><i className={telemetry.criticalLoadServed ? 'healthy' : 'idle'} /><span><b>Critical load service</b><small>{num(telemetry.unmetLoadKw)} kW unmet load</small></span><strong>{telemetry.criticalLoadServed ? 'Served' : 'Alert'}</strong></button><button onClick={() => setSelectedSystem('Resilience control')}><i className={resilience?.connectivity_status === 'ONLINE' ? 'healthy' : 'idle'} /><span><b>Resilience control</b><small>{resilienceLatest?.dispatch_mode ?? 'No resilience result'}</small></span><strong>{resilience?.connectivity_status ?? 'Unknown'}</strong></button></div><div className="system-detail"><small>SELECTED SYSTEM</small><b>{selectedSystem}</b><span>{selectedSystem === 'Resilience control' ? resilienceLatest?.reasoning ?? 'No resilience reasoning is available.' : selectedSystem === 'Battery storage' ? `${num(telemetry.batterySocKwh)} kWh stored; current battery flow is ${num((latestDispatch?.battery_charge_kw ?? 0) - (latestDispatch?.battery_discharge_kw ?? 0))} kW.` : `${num(telemetry.unmetLoadKw)} kW unmet load; fuel remaining is ${num(telemetry.fuelRemainingLitres)} L.`}</span></div></>}
    {section === 'AI & Forecast' && (nextForecast ? <><div className="detail-grid"><DetailCard label="Next Load p50" value={`${num(nextForecast.total_load_kw_p50)} kW`} detail={`${nextForecast.timestamp} · +${nextForecast.step_ahead}h`} icon={BrainCircuit} /><DetailCard label="Renewable p50" value={`${num(nextForecast.solar_power_kw_p50 + nextForecast.wind_power_kw_p50)} kW`} detail={`Solar ${num(nextForecast.solar_power_kw_p50)} · wind ${num(nextForecast.wind_power_kw_p50)}`} icon={Leaf} /><DetailCard label="Net Load p50" value={`${num(nextForecast.net_load_kw_p50)} kW`} detail={`${Math.round(nextForecast.confidence_score * 100)}% confidence · ${nextForecast.forecast_mode}`} icon={Gauge} /><DetailCard label="Weather Risk" value={nextForecast.storm_risk_flag ? 'Storm' : 'Clear'} detail={nextForecast.turbine_cutout_risk ? 'Turbine cutout risk' : `${num(nextForecast.temperature_c_pred)}°C · ${num(nextForecast.wind_speed_ms_pred)} m/s`} icon={Wind} /></div><div className="data-list">{forecast.rows.map((row) => <div key={row.timestamp}><b>+{row.step_ahead}h</b><span>{num(row.total_load_kw_p50)} kW load</span><span>{num(row.solar_power_kw_p50)} solar / {num(row.wind_power_kw_p50)} wind</span><span>{Math.round(row.confidence_score * 100)}% confidence</span></div>)}</div></> : <Unavailable message={forecast?.error ?? 'Forecast service response is unavailable.'} />)}
    {section === 'Digital Twin' && <><div className="detail-grid"><DetailCard label="Telemetry History" value={`${telemetryHistory.length} samples`} detail={provenance?.data_mode ?? 'Simulation mode'} icon={Activity} /><DetailCard label="Load Served" value={telemetry.criticalLoadServed ? '100%' : 'Partial'} detail={`${num(telemetry.unmetLoadKw)} kW unmet`} icon={Gauge} /><DetailCard label="Weather Source" value={provenance?.weather_source ?? 'Unavailable'} detail={provenance?.weather_sample ?? 'No sample name'} icon={CloudSun} /><DetailCard label="Latest Timestamp" value={telemetry.timestamp.replace('T', ' ').slice(0, 16)} detail="Backend Digital Twin output" icon={Battery} /></div><div className="data-list">{telemetryHistory.map((row) => <div key={row.timestamp}><b>{row.timestamp.slice(11, 16)}</b><span>{num(row.totalLoadKw)} kW load</span><span>{num(row.solarPowerKw)} solar / {num(row.windPowerKw)} wind</span><span>{num(row.batterySocKwh)} kWh SOC</span></div>)}</div></>}
    {section === 'Environment' && <div className="detail-grid"><DetailCard label="Ambient Temperature" value={`${num(telemetry.temperatureC)}°C`} detail="Digital Twin weather input" icon={CloudSun} /><DetailCard label="Wind Speed" value={`${num(telemetry.windSpeedMs)} m/s`} detail={`${num(telemetry.windPowerKw)} kW wind generation`} icon={Wind} /><DetailCard label="Solar Irradiance" value={`${num(telemetry.irradianceWm2)} W/m²`} detail={`${num(telemetry.solarPowerKw)} kW solar generation`} icon={Zap} /><DetailCard label="Forecast Risk" value={nextForecast?.storm_risk_flag ? 'Storm alert' : 'No storm'} detail={nextForecast?.turbine_cutout_risk ? 'Turbine cutout risk' : 'No turbine cutout risk'} icon={Leaf} /></div>}
    {section === 'Reports' && <div className="report-summary"><div><FileText /><h3>Bharati backend summary</h3><p>{reportRows.map(([metric, value]) => `${metric}: ${value}`).join(' · ')}. {provenance?.data_mode ?? 'Simulation'} data from {provenance?.weather_source ?? 'the configured weather source'}.</p></div><button onClick={downloadReport}><ArrowDownToLine size={17} /> Download CSV</button></div>}
  </section>
}
